version: "0.2"
words:
  - arange
  - informationally
  - injectively
  - overriden
  - Pinzón
  - preceeding
  - submatrix
  - subproblems
ignoreWords:
  - IIFE
  - katex
  - mathjax
  - lzutf8
  - hyphenator
  - xhtm
  - elems
  - lmroman
  - lmsans
  - monokai
  - searchcursor
  - scrollpastend
  - keymap
  - autorefresh
