version: "0.2"
words:
  - informationally
  - injectively
  - submatrix
  - subproblems
  - preceeding
  - overriden
  - Pinzón
ignoreWords:
  - IIFE # https://developer.mozilla.org/en-US/docs/Glossary/IIFE
  - katex
  - mathjax
  - lzutf8
  - hyphenator
  - xhtm
  - elems
  - lmroman
  - lmsans
  - monokai
  - searchcursor
  - scrollpastend
  - keymap
  - autorefresh
